name: Lint

on:
  pull_request:
    branches:
      - dev

env:
  NODE_VERSION: 24

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH for Private GitHub Packages (Using the SSH key for @BluetailDeployBot)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOYBOT_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "Using SSH key for deploybot authentication"

      - name: Test SSH Authentication
        run: ssh -o StrictHostKeyChecking=no -T git@github.com || true

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa" npm ci

      - name: Code Linting
        run: npm run lint
